# Kibana .yml internal config

server.host: "0"
server.shutdownTimeout: "5s"
elasticsearch.hosts: [ "https://elasticsearch:9200" ]
monitoring.ui.container.elasticsearch.enabled: true
enterpriseSearch.host: 'https://localhost:3002'
